# -*- coding: utf-8 -*-
"""Achore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FwH1sZE673wCGLs6vmsCC_zab5wCEkhT
"""

import wikipedia as wiki

def get_wiki_professions(name):
 
 anchor_content = (((wiki.page(name,auto_suggest=False)).content).replace(' and ',', ').replace('.','. '))
#  print(anchor_content)
 split_type = [' is a ',' is an ',' was a ',' was an ']
 
 split_type_list = []
 prefix = None
 for x in split_type:
   if x in anchor_content:
     prefix = x
     split_type_index = anchor_content.find(prefix)
    #  print(index_split_type)
     pro = split_type_list.append(split_type_index)
   else:
     split_type_list.append(1000)

 low_index = split_type[split_type_list.index(min(split_type_list))]
#  print(low_index)   
     

 if prefix is None:
   return None

 final_split = anchor_content.split(low_index)[1].split('. ')[0].split(', ')
#  print(final_split)
 final_professions = [anchor_content.lower() for anchor_content in final_split]
 return final_professions

get_wiki_professions("Matt Lauer")

def check_wiki_professions(list_profession):
  general_professions = ['host','presenter','journalist','news anchor','correspondent','anchor']

  check_individual_prof = []
  for x in general_professions:
    final_check= [(x in y) for y in list_profession]
    check_individual_prof.append(any(final_check))
    # print(x)
  
  if (any(check_individual_prof)==True):
    return True
  else:
    return False

check_wiki_professions(get_wiki_professions("Matt Lauer"))

# From top 5 anchor we get most probable and in that show
# Anchor_list = "Colleen-Williams_Ashwini-Bhave_Elaine-Quijano_Becky-Hobbs_Heidi-Collins"
def get_correct_anchor(top_5):
  top_5_list = (top_5.replace('-',' ').replace('_',',')).split(',')
  print(top_5_list)
  for x in top_5_list:
    # print(x)
    if check_wiki_professions(get_wiki_professions(x)) is True:
      return x
  else:
    return "Not found"

get_correct_anchor('Jack-Tunney_Gerry-Dee_Elisha-Cook-Jr._Ben-Welden_Hoyt-Axton')

